version: "3.9"
services:
  app:
    build: ./app
    entrypoint: /usr/src/app/server-entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  worker:
    build:
      context: ./app
    entrypoint: /usr/src/app/worker-entrypoint.sh
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - app
      - db
      - redis
  db:
    image: postgres
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
  redis:
    image: redis:7.0.5-alpine
    expose:
      - 6379

volumes:
  postgres_data: